SBoudrias/mem-fs-editor

README.md
actions/commit.js
actions/copy.js
actions/delete.js
test/copy.js
test/delete.js
test/util.js
util/util.js

@SBoudrias This PR contains breaking change!
This PR attempts to address a list of issues I found around copy/delete.
* #15
* Currently, `fs.delete` only deletes files that is buffered in `mem-fs` store. It seems like [this is intentional](https://github.com/SBoudrias/mem-fs-editor/blob/master/test/delete.js#L24), but I found this a little cumbersome in many Yeoman generator use cases. So the new implementation will delete both uncommitted files in store, as well as physical files that has not been read into the store. **This is a breaking change**
* Currently, `copy` only support `from` to be either a file, or a glob pattern that uses `*`. But [not all glob patterns use `*`](https://github.com/isaacs/node-glob#globhasmagicpattern-options). The new implementation supports `from` to be the …

Unified glob usage across copy/delete - for better directory support.

---

README.md
actions/move.js
index.js
test/move.js

Implements `move` function

---

actions/copy.js
actions/delete.js
package.json
test/copy.js
test/util.js
util/util.js

Supersedes PR [#30](https://github.com/SBoudrias/mem-fs-editor/pull/30). The previous implementation of array and multi-glob support caused the code to behave differently when given an array. This implementation embraces arrays and keeps the handling consistent.
When given an array the `util` methods will now iterate over the arrays and apply the pre-existing logic to each item in the array. The `getCommonPath` method will then additionally normalize the array to a single common string using `commondir`.
Both `.copy()` and `.delete()` have been updated to always use `globby.sync` in place of `glob.sync` and `multimatch` in place of `minimatch.match`.
None of the original tests were modified in any way. Additional tests were added to specifically test array handling.
@SBoudrias I'm not …

Added support for arrays of paths and globs.

---

actions/write-json.js
test/write-json.js

Otherwise the scaffolded package.json of generator will not have a newline at the end

append a newline to writeJson

---

actions/read.js
test/read.js

This fixes #36 by testing whether `options.defaults` is a string or Buffer value rather than a truthy value, allowing an empty string as a default value. 
Fortunately there was a test passing in a Buffer rather than a string, I would not have caught that use case!

Allow empty string value in the defaults option for read().

---

actions/read-json.js
package.json
test/read-json.js

Fixs #38 
New error message reads:
```
Error: Could not parse JSON in file: /Users/brianlai/Documents/projects/gh/mem-fs-editor/test/fixtures/file-tpl.txt. Detail: Unexpected token <
at EditionInterface.module.exports [as readJSON] (/Users/brianlai/Documents/projects/gh/mem-fs-editor/actions/read-json.js:8:13)
at Context.<anonymous> (/Users/brianlai/Documents/projects/gh/mem-fs-editor/test/read-json.js:41:45)
...
```

Enhance error message to include file name when failed to parse JSON

---

README.md

Currently the docs do not match the actual behavior of the library.
`readJSON` never actually attempts to read a non-existent file, but guards it with an `exists` call: https://github.com/SBoudrias/mem-fs-editor/blob/2c0ad362d9ed854b1558e5a0fbc0af3a7bd26e59/lib/actions/read-json.js#L4-L12

Fix readJSON docs

---

.github/workflows/test.yml
README.md
__tests__/copy-tpl.js
__tests__/copy.js
__tests__/fixtures/file-circular.txt
lib/actions/append.js
lib/actions/copy-tpl.js
lib/actions/copy.js
package.json

- When passing a circular object function context to `copyTemplate()` deep-extend throws an error.
So use spread (node >= 8.3.0) instead of deep-extend where applicable.
- Implement `options.processDestinationPath` support when `from` is a glob and remove ejs extension by default for `copyTpl()`.
- Add github workflow
- Add to engines node >= 10

Misc improvements and fixes.

---

.github/workflows/test.yml
package-lock.json
package.json

The globby dependency fast-glob version 3 disallows `\\`, this change broke windows support.
Reverting to globby 9.x
A fix would be to replace windows paths with posix ones. Since I am targeting yeoman-generator 4.x, I prefer to revert, and revisit later.
Others improvements:
- Remove glob dependency, globby seems to provide the required api.
- Replace rimraf with recursive rmdirSync. (Node 12)
- Replace mkdirp with recursive mkdirSync. (Node 10).
@SBoudrias can you do a patch release?
Thanks.

Revert globby to 9.x

---

README.md
__tests__/append-tpl.js
lib/actions/append-tpl.js
lib/index.js

Add: appendTpl(filepath, contents, context[, templateOptions[, [options]])
This acts as an overload to append() allowing the new content to be parsed as an ejs template prior to appending.
The behaviour of append() is not changed.

add appendTpl

---

README.md
__tests__/__snapshots__/commit.js.snap
__tests__/copy-async.js
__tests__/copy.js
__tests__/fixtures/file-(specia!-char$).txt
lib/actions/copy.js

I tried to keep the changes minimal, while making this to work.
A test was added with a file containing special glob characters, that fails to copy without this option.
I also had to update some other test as I needed to add a new files in fixture dir.

Add noGlob option (fix #75)

---

lib/actions/copy.js

when noGlob is passed, many glob operations are still applied.

optimizations

---

lib/actions/commit.js
package-lock.json
package.json

mem-fs@2.3.0 allows to filter files before adding to stream.
This PR adds filter that matches the first in-stream filter.

add default filter to stream

---

README.md
__tests__/__snapshots__/dump.js.snap
__tests__/dump.js
lib/actions/dump.js

`dump` can return false positives when using pattern.
If a file that matches the pattern is read and added to the memory fs, that file will be returned at dump with pattern.

apply state filter to dump with pattern

---

.github/workflows/test.yml
README.md
__tests__/commit-file-async.spec.ts
__tests__/commit.spec.ts
__tests__/dump.spec.ts
package-lock.json
package.json
src/actions/commit-file-async.ts
src/actions/commit.ts
src/index.ts
src/transform.ts
vitest.config.ts

- use pipeline from `mem-fs`.
- bump node to v18.0.0 matching `mem-fs`.
- add coverage.
- move `mem-fs` to peer-dependencies. `mem-fs` is not instantiated directly, but the editor requires specific features from `mem-fs`.
Having it in peer dependencies is more appropriate.
- `commitFileAsync` used to add a missing file to `mem-fs`, it's not require anymore since `mem-fs` now recreates the fs state using emitted files.
- decouple `commitFileAsync` from `mem-fs-editor` instance.
Can be used to create custom commit pipeline without mem-fs-editor instance:
```
await memFs.pipeline(createCommitTransform());
```
- re-export `{ PipelineOptions, FileTransform }` for convenience.

use pipeline from mem-fs@4

---

package-lock.json
package.json

Use fixed version to avoid conflicts in the future
node v14 and v16 support were dropped in a patch version.

isbinaryfile does not follow semver for supported node, use fixed version

---

__tests__/copy-async.spec.ts
__tests__/copy-tpl-async.spec.ts
__tests__/copy-tpl.spec.ts
__tests__/copy.spec.ts
src/actions/copy-async.ts
src/actions/copy.ts
src/actions/write.ts
src/index.ts

Rework to keep file history when copying

keep file history

---

package-lock.json
package.json

isbinaryfile does not respect node for major versions.
- bump isbinaryfile.
- accept newer isbinaryfile if other package already uses it to avoid duplications in node_modules.

chore: update isbinaryfile and accept newer versions

---

.eslintrc.json
README.md
package.json
src/actions/commit-file-async.ts
src/transform.ts

Workaround https://github.com/nodejs/node/pull/55270

fix: replace Duplex with Transform

---

__tests__/append-tpl.spec.ts
__tests__/copy-async.spec.ts
__tests__/copy.spec.ts
__tests__/read.spec.ts
src/actions/append.ts
src/actions/copy-tpl.ts
src/actions/copy.ts
src/actions/read-json.ts
src/actions/read.ts

chore: types adjusts

---

__tests__/read.spec.ts
src/actions/read.ts

I don't think #310 worked as expected. It did fix cases where `null` cannot be returned, but the content type didn't work.
I add type tests in vitest to validate and enforce the right behavior is maintained in the future.
I'd appreciate if you can double-check and make sure this change does make sense @mshima! Thanks!

Fix: Type inference of read method
